### create a payoff matrix 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans


payoff_matrix = np.array(
     # Point strategies
     #    C1      C2      C3      C4
    [[(0, 0), (0, 0), (0, 0), (0, 0)], #
     [(0, 0), (0, 0), (0, 0), (0, 0)], #
     [(0, 0), (0, 0), (0, 0), (0, 0)]] #
)


# print("Generating payoff matrix\n", np.zeros((3,4,2)) )

print(payoff_matrix)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]


### some strategies 


In [ ]:

# Strategy 2: Farthest Point Strategy
def find_farthest_point(points, centers):
    farthest_dist = -1
    farthest_point = None
    for point in points:
        min_distance = min(np.linalg.norm(point - c) for c in centers)
        if min_distance > farthest_dist:
            farthest_dist = min_distance
            farthest_point = point
    return farthest_point

# Strategy 3: K-Means++ Initialization
def kmeans_pp_strategy(X, num_clusters):
    kmeans_pp = KMeans(n_clusters=num_clusters, init='k-means++')
    kmeans_pp.fit(X)
    kmeans_pp_positions = kmeans_pp.cluster_centers_
    return kmeans_pp_positions




### find closest centroid 

In [2]:
import pandas as pd
import numpy as np

# Example DataFrame
data = {
    'X': [1, 2, 3, 5, 6, 7],
    'Y': [1, 2, 3, 5, 6, 7],
    'Z': [1, 2, 3, 5, 6, 7],
    'centroid': [0, 0, 0, 0, 0, 0]
}

df = pd.DataFrame(data)

# Example centroids array
centroids = np.array([[1, 1], [2, 2], [6, 6], [7, 7]])

# Function to find the closest centroid
def find_closest_centroid(point, centroids):
    distances = np.linalg.norm(centroids - point, axis=1)
    closest_centroid_idx = np.argmin(distances)
    return closest_centroid_idx

# Iterate through each row and update 'centroid' column with the closest centroid
for idx, row in df.iterrows():
    point = np.array([row['X'], row['Y']])
    closest_idx = find_closest_centroid(point, centroids)
    df.at[idx, 'centroid'] = closest_idx

print(df)

   X  Y  Z  centroid
0  1  1  1         0
1  2  2  2         1
2  3  3  3         1
3  5  5  5         2
4  6  6  6         2
5  7  7  7         3
